function [dX,dY,dZ] = F(t,X,Y,Z)
  dX = zeros(1, length(X))
  dY = zeros(1, length(Y))
  dZ = zeros(1, length(Z))
  dX(1) = fX1(t, X, Y, Z)
  dX(2) = fX2(t, X, Y, Z)
  dX(3) = fX3(t, X, Y, Z)
  dY(1) = fY1(t, X, Y, Z)
  dY(2) = fY2(t, X, Y, Z)
  dZ(1) = fZ1(t, X, Y, Z)
  dZ(2) = fZ2(t, X, Y, Z)
  dZ(3) = fZ3(t, X, Y, Z)
endfunction